# Generated by Django 3.2.4 on 2021-06-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.FloatField()),
                ('in_stock', models.BooleanField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
