# Generated by Django 3.2.4 on 2021-06-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeStore', '0003_auto_20210625_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeproducts',
            name='discountPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafeproducts',
            name='rate',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafeproducts',
            name='savePrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafeproducts',
            name='tags',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cafeproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
