# Generated by Django 3.2.4 on 2021-06-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeStore', '0004_auto_20210625_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeproducts',
            name='pack',
            field=models.IntegerField(default=2),
        ),
    ]
